---
# This tracker discovers new devices on boot and in regular intervals and
# tracks Bluetooth low-energy devices periodically based on interval_seconds
# value.
#
# https://www.home-assistant.io/integrations/bluetooth_le_tracker/
#

device_tracker:
  # - platform: bluetooth_le_tracker
  #   interval_seconds: 15
  #   consider_home: 150
  #   track_new_devices: yes
  - platform: bluetooth_tracker
    interval_seconds: 15
    consider_home: 150
    track_new_devices: true
