---
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - person
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    entity_globs:
      - sensor.pi_hole_*
      - sensor.*_update_state
      - device_tracker.*
