---
# The http integration serves all files and data required for the
# Home Assistant frontend.
#
# https://www.home-assistant.io/integrations/http
#
http:
  ssl_certificate: !secret SSL_CERTIFICATE
  ssl_key: !secret SSL_KEY
