---
recorder:
  purge_keep_days: 3
  include:
    domains:
      - sensor
      - switch
      - media_player
      - person
      - binary_sensor
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    entity_globs:
      - sensor.pi_hole_*
      - sensor.*_update_state
      - device_tracker.*
      - binary_sensor.*_update_available
      - binary_sensor.updater
