---
alias: Mark person as extended away
id: 0A6EF62B-DB92-466C-A415-CBA5B24DFAE5
trigger:
  - platform: state
    entity_id: input_select.remco_status_dropdown
    to: 'Away'
    for:
      hours: 24
  - platform: state
    entity_id: input_select.miriam_status_dropdown
    to: 'Away'
    for:
      hours: 24
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'input_select.remco_status_dropdown' %}
          input_select.remco_status_dropdown
        {% else %}
          input_select.miriam_status_dropdown
        {% endif %}
      option: Extended Away
